name = "LogpdfExpectation"
uuid = "70ff922c-62d4-418d-abfc-e284e489b734"
authors = ["Mykola Lukashchuk <nikola.lukashuk@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
julia = "1.10"
Distributions = "0.25"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[targets]
test = ["Test", "ReTestItems", "StableRNGs"]
